version: 2
updates: 
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Stockholm"
    labels:
      - "npm dependencies"
    commit-message: 
      prefix: "npm"
  
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Stockholm"
    labels:
      - "composer dependencies"
    commit-message: 
      prefix: "npm"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Stockholm"
    labels:
    - "pip dependencies"
    commit-message: 
    prefix: "pip"
    
    rebase-strategy: "enabled"
