version: 2
updates: 
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "Thursday"
      timezone: "Europe/Stockholm"
      time: "8:00"
    labels:
      - "npm dependencies"
    commit-message: 
      prefix: "npm"
  
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "Thursday"
      timezone: "Europe/Stockholm"
      time: "8:00"
    labels:
      - "composer dependencies"
    commit-message: 
      prefix: "npm"

  - package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "Thursday"
    timezone: "Europe/Stockholm"
    time: "8:00"
  labels:
    - "pip dependencies"
  commit-message: 
    prefix: "pip"
    
    rebase-strategy: "enabled"
